# -*- coding: utf-8 -*-
"""Formats the SZM feasibility results into two outputs:

  (1) tab_montecarlo_compact.tex  -- compact table for the BOOK (Study B),
      from the terrible device to the cheap three-and-a-half-digit one,
      showing the cost knee.
  (2) montecarlo_full.html + .csv -- the full grid (Study A) for electronic
      publication (GitHub + QR).

It is the "formatter code" that accompanies the POC. It reads the CSVs
generated by sweep_feasibility.py; it does not run the simulation.
"""
import csv
import html
import sys
from pathlib import Path

SP = Path(__file__).parent

# labels for the Study B rows (book), in CSV order
LABELS_B = {
    (2, 0.1, 0.01):     ("Terrible",                False),
    (2, 0.05, 0.005):   ("Poor",                     False),
    (2, 0.02, 0.0001):  ("Reasonable (2 digits)",   False),
    (3, 0.02, 0.0001):  ("\\textbf{Cheap: 3\\textonehalf\\ digits}", True),
    (4, 0.02, 0.0001):  ("4 digits",                False),
    (3, 0.01, 0.0001):  ("3\\textonehalf\\ digits, less noise", False),
}


def f2(x):
    return f"{float(x):.2f}"


def pct(x):
    return f"{float(x)*100:.3f}\\,\\%"


def pct_noise(x):
    # last-digit noise: an integer, as in the book's table
    return f"{round(float(x)*100)}\\,\\%"


# ---------------------------------------------------------------- BOOK (B)
def generate_compact_latex(csv_b: Path, out: Path):
    rows = list(csv.DictReader(csv_b.open(encoding="utf-8")))
    L = []
    L.append("% Generated by format_tables_szm.py -- do not edit by hand.")
    L.append("% Compact table (Study B). The full grid (Study A) is published")
    L.append("% at .../tabelas/montecarlo/, alongside this listing.")
    L.append("\\begin{table}[H]")
    L.append("\\centering")
    L.append("\\caption{Feasibility of the SZM by device quality (prec.\\ 20, "
             "20,000 sessions per scenario, three devices with a unanimity "
             "protocol that \\emph{reprocesses until success}). The value is "
             "always recovered, except for the extremely rare \\emph{unanimous "
             "error} (the three devices agree on the \\emph{same} incorrect "
             "value): hence the recovery rate of 99.99\\,\\% rather than "
             "100\\,\\%. The recommended operating point (green) is a cheap "
             "3\\textonehalf-digit device: it recovers with negligible "
             "reprocessing and in fewer rounds than a 2-digit one. Going up to "
             "4 digits saves only two rounds, without justifying the cost.}")
    L.append("\\label{tab:montecarlo}")
    L.append("\\small")
    L.append("\\setlength{\\tabcolsep}{5pt}")
    L.append("\\renewcommand{\\arraystretch}{1.2}")
    L.append("\\begin{tabular}{@{}lccccc@{}}")
    L.append("\\toprule")
    L.append("Scenario & \\makecell{d\\\\(dig./read)} & "
             "\\makecell{noise on\\\\last digit} & rounds & "
             "\\makecell{recovery\\\\rate} & "
             "\\makecell{reproc.\\\\per block} \\\\")
    L.append("\\midrule")
    for r in rows:
        key = (int(r["d"]), float(r["p_last"]), float(r["p_block"]))
        label, highlight = LABELS_B.get(key, (f"d={r['d']}", False))
        line = (f"{label} & {r['d']} & {pct_noise(r['p_last'])} & {r['rounds']} & "
                f"{pct(r['recovery_rate'])} & {f2(r['refetches_per_block'])}")
        if highlight:
            line = "\\rowcolor{green!12}\n" + line
        L.append(line + " \\\\")
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table}")
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"  {out.name}: {len(rows)} rows")


# ------------------------------------------------------------ ELECTRONIC (A)
CSS = """
:root{color-scheme:light dark;--bg:#f4f6f7;--fg:#1a2327;--card:#fff;
--muted:#5b6b72;--acc:#0f6d7a;--line:#dce3e5;--warn:#b45309}
@media(prefers-color-scheme:dark){:root{--bg:#12181a;--fg:#e6edef;
--card:#1b2427;--muted:#93a4aa;--acc:#4fd0e0;--line:#2a363a;--warn:#f0b35b}}
*{box-sizing:border-box}
body{margin:0;font:15px/1.5 -apple-system,Segoe UI,Roboto,Arial,sans-serif;
background:var(--bg);color:var(--fg)}
.wrap{max-width:1000px;margin:0 auto;padding:24px 18px 60px}
h1{font-size:1.4rem;margin:.2em 0}
.sub{color:var(--muted);margin:.2em 0 1.2em}
.card{background:var(--card);border:1px solid var(--line);border-radius:12px;
padding:14px 16px;margin:0 0 18px}
table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums}
th,td{padding:6px 10px;text-align:right;border-bottom:1px solid var(--line)}
th{position:sticky;top:0;background:var(--card);text-align:right;font-size:.82rem;
color:var(--muted)}
td:first-child,th:first-child{text-align:left}
tbody tr:hover{background:color-mix(in srgb,var(--acc) 8%,transparent)}
.scroll{overflow-x:auto}
.btn{display:inline-block;padding:10px 16px;border-radius:9px;background:var(--acc);
color:#fff;text-decoration:none;font-weight:600}
footer{color:var(--muted);font-size:.8rem;margin:36px 0 0;border-top:1px solid var(--line);
padding-top:14px}
footer a{color:var(--acc)}
"""

COLS_HTML = [
    ("d", "d (dig./read)"), ("p_last", "last-digit noise"),
    ("p_block", "block noise"), ("rounds", "rounds"),
    ("recovery_rate", "recovery"),
    ("frac_wrong_unanimity", "residual failure"),
    ("refetches_per_block", "refetch/block"),
    ("refetches_per_session", "refetch/session"),
    ("worst_case_attempts", "worst case"),
]


def generate_full_html(csv_a: Path, out_html: Path, out_csv: Path):
    rows = list(csv.DictReader(csv_a.open(encoding="utf-8")))
    out_csv.write_text(csv_a.read_text(encoding="utf-8"), encoding="utf-8")

    def cell(col, v):
        if col in ("recovery_rate",):
            return f"{float(v)*100:.3f}%"
        if col in ("p_last", "p_block", "frac_wrong_unanimity",
                   "refetches_per_block", "refetches_per_session"):
            return f"{float(v):.4f}".rstrip("0").rstrip(".") or "0"
        return str(v)

    trs = []
    for r in rows:
        tds = "".join(f"<td>{html.escape(cell(c, r[c]))}</td>" for c, _ in COLS_HTML)
        trs.append(f"<tr>{tds}</tr>")
    ths = "".join(f"<th>{html.escape(t)}</th>" for _, t in COLS_HTML)
    body = f"""<div class="wrap">
<h1>SZM &mdash; Monte Carlo simulation (full table)</h1>
<p class="sub">Feasibility study of the Successive Zooms Method.
{len(rows)} configurations &middot; 20 000 sessions each &middot; precision 20 digits.</p>
<div class="card">
<b>How to read.</b> Three noisy devices read each block; if they disagree, the
monitor orders a reprocess until there is unanimity. The value is recovered
almost always &mdash; the <i>residual failure</i> is the rare <i>wrong unanimity</i>
(the three agree on the same wrong value), which the majority-of-3 does not
detect. <code>d</code> is the number of digits read per round; more digits =
fewer rounds, at the cost of a more expensive device.
</div>
<div class="card">
<b>Downloads.</b> The full grid and the three programs that produce it:
<p style="margin:10px 0 0">
<a class="btn" href="montecarlo_full.csv" download>Full table (CSV)</a>
<a class="btn" href="../../listagens/volIII/listagemAG.8/">Simulator (Listing AG.8)</a>
<a class="btn" href="../../listagens/volIII/listagemAG.9/">Sweeper (Listing AG.9)</a>
<a class="btn" href="../../listagens/volIII/listagemAG.10/">Formatter (Listing AG.10)</a>
</p>
<p class="sub" style="margin:10px 0 0">The simulator and the sweeper generate the data; the
formatter produces this table and the book's compact version. Fixed seeds
&mdash; whoever runs it gets exactly these numbers.</p>
</div>
<div class="card scroll"><table><thead><tr>{ths}</tr></thead>
<tbody>{''.join(trs)}</tbody></table></div>
<footer>Generated by <code>format_tables_szm.py</code> from the simulator
<code>szm_feasibility.py</code>. Fixed seeds &mdash; reproducible results.
<a href="https://github.com/impnet-br/metafora-bolholandia-figuras">Repository</a>.
</footer></div>"""
    doc = ('<!doctype html><html lang="en"><head><meta charset="utf-8">'
           '<meta name="viewport" content="width=device-width,initial-scale=1">'
           '<title>SZM &mdash; full Monte Carlo</title>'
           f'<style>{CSS}</style></head><body>{body}</body></html>')
    out_html.write_text(doc, encoding="utf-8")
    print(f"  {out_html.name}: {len(rows)} rows + CSV")


def main():
    print("Formatting:")
    generate_compact_latex(SP / "feas_study_B_book.csv",
                           SP / "tab_montecarlo_compact.tex")
    generate_full_html(SP / "feas_study_A_full.csv",
                       SP / "montecarlo_full.html",
                       SP / "montecarlo_full.csv")
    return 0


if __name__ == "__main__":
    sys.exit(main())
